version: "3"

services:
    database:
        image: postgres:11-alpine
        environment:
            POSTGRES_USER: main
            POSTGRES_PASSWORD: main
            POSTGRES_DB: main
        ports: [5432]

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
    
    rabbitmq:
        image: rabbitmq:3.7-management
        ports: [5672, 15672]

    mailcatcher:
        image: schickling/mailcatcher
        ports: [1025, 1080]
